# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "127.0.0.1:3307"
my_user = "root"
my_pass = "newpass"

# Elasticsearch address
es_addr = "127.0.0.1:9200"

# Path to store data, like master.info, and dump MySQL data
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001111111

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# MySQL data source
[[source]]
schema = "projectkdb"

# Only below tables will be synced into Elasticsearch.
# "test_river_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
tables = ["order_tbl", "ticket_tbl","arrangement_tbl","subClasses_tbl","activity_tbl","activity_en_tbl","activity_ch_tbl","subClasses_en_tbl","subClasses_ch_tbl","city_en_tbl","city_ch_tbl","user_tbl","userexternal_tbl","braintreelog_tbl","voucher_tbl"]
#tables = ["order_tbl"]
[[rule]]
schema = "projectkdb"
table = "order_tbl"
index = "projectkdb"
type = "order_tbl"
[[rule]]
schema = "projectkdb"
table = "subClasses_ch_tbl"
index = "projectkdb"
type = "subClasses_ch_tbl"
[[rule]]
schema = "projectkdb"
table = "city_en_tbl"
index = "projectkdb"
type = "city_en_tbl"
[[rule]]
schema = "projectkdb"
table = "city_ch_tbl"
index = "projectkdb"
type = "city_ch_tbl"
[[rule]]
schema = "projectkdb"
table = "user_tbl"
index = "projectkdb"
type = "user_tbl"
[[rule]]
schema = "projectkdb"
table = "userexternal_tbl"
index = "projectkdb"
type = "userexternal_tbl"
[[rule]]
schema = "projectkdb"
table = "braintreelog_tbl"
index = "projectkdb"
type = "braintreelog_tbl"
[[rule]]
schema = "projectkdb"
table = "voucher_tbl"
index = "projectkdb"
type = "voucher_tbl"
[[rule]]
schema = "projectkdb"
table = "ticket_tbl"
index = "projectkdb"
type = "ticket_tbl"
[[rule]]
schema = "projectkdb"
table = "arrangement_tbl"
index = "projectkdb"
type = "arrangement_tbl"
[[rule]]
schema = "projectkdb"
table = "subClasses_tbl"
index = "projectkdb"
type = "subClasses_tbl"
[[rule]]
schema = "projectkdb"
table = "activity_tbl"
index = "projectkdb"
type = "activity_tbl"
[[rule]]
schema = "projectkdb"
table = "activity_en_tbl"
index = "projectkdb"
type = "activity_en_tbl"
[[rule]]
schema = "projectkdb"
table = "activity_ch_tbl"
index = "projectkdb"
type = "activity_ch_tbl"
[[rule]]
schema = "projectkdb"
table = "subClasses_en_tbl"
index = "projectkdb"
type = "subClasses_en_tbl"

# Below is for special rule mapping
#[[rule]]
#schema = "test"
#table = "test_river"
#index = "river"
#type = "river"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    #[rule.field]
    # This will map column title to elastic search my_title
    # title="es_title"
    # This will map column tags to elastic search my_tags and use array type
    # tags="my_tags,list"
    # This will map column keywords to elastic search keywords and use array type
    # keywords=",list"

# wildcard table rule, the wildcard table must be in source tables
#[[rule]]
#schema = "test"
#table = "test_river_[0-9]{4}"
#index = "river"
#type = "river"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
#    [[rule.fields]]
#    mysql = "title"
#    elastic = "es_title"
